// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlaySkriptaZaAchivmenteInScoreBoarde
{
        public const string achievement_get_100_crystals = "CgkImp-w7uYcEAIQAQ"; // <GPGSID>
        public const string achievement_get_5000_crystals = "CgkImp-w7uYcEAIQBQ"; // <GPGSID>
        public const string achievement_get_20000_crystals = "CgkImp-w7uYcEAIQCA"; // <GPGSID>
        public const string leaderboard_240_sec_leaderboard = "CgkImp-w7uYcEAIQBg"; // <GPGSID>
        public const string achievement_get_200_crystals = "CgkImp-w7uYcEAIQAg"; // <GPGSID>
        public const string achievement_get_1000_crystals = "CgkImp-w7uYcEAIQBA"; // <GPGSID>
        public const string achievement_get_500_crystals = "CgkImp-w7uYcEAIQAw"; // <GPGSID>
        public const string leaderboard_60_sec_leaderboard = "CgkImp-w7uYcEAIQCg"; // <GPGSID>
        public const string leaderboard_infinity_leaderboard = "CgkImp-w7uYcEAIQCQ"; // <GPGSID>
        public const string achievement_get_10000_crystals = "CgkImp-w7uYcEAIQBw"; // <GPGSID>

}

